In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
iris = load_iris()

In [9]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [11]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [13]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [15]:
from sklearn.model_selection import cross_val_score
lr = cross_val_score(LogisticRegression(),iris.data,iris.target)
lr

C:\Users\dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [16]:
rf = cross_val_score(RandomForestClassifier(),iris.data,iris.target)

In [17]:
rf

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [25]:
sv = cross_val_score(SVC(kernel = 'linear'),iris.data,iris.target)
sv

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [19]:
sv

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [20]:
lr.mean()

0.9733333333333334

In [26]:
sv.mean()

0.9800000000000001

In [22]:
rf.mean()

0.9600000000000002