In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.datasets import load_digits
digits = load_digits()

In [3]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [4]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size = 0.3)

In [7]:
len(x_train)

1257

In [8]:
lr = LogisticRegression()

In [9]:
lr.fit(x_train,y_train)

C:\Users\dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [15]:
lr.score(x_test,y_test)

0.9925925925925926

In [16]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.975925925925926

In [12]:
rf = RandomForestClassifier()

In [17]:
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9666666666666667

In [18]:
from sklearn.model_selection import KFold
kf = KFold(n_splits =3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [20]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [27]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [28]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

C:\Users\dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

In [29]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.975925925925926

In [30]:
from sklearn.model_selection import StratifiedKFold

In [32]:
folds = StratifiedKFold(n_splits =3)

In [36]:
from sklearn.model_selection import cross_val_score
lr = cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

In [37]:
sv = cross_val_score(SVC(),digits.data,digits.target)

In [38]:
rf = cross_val_score(RandomForestClassifier(),digits.data,digits.target)

In [39]:
rf.mean()

0.9382544103992572

In [40]:
sv.mean()

0.9632838130609718

In [42]:
lr.mean()

0.9137650882079852

In [43]:
model = SVC()
model.fit(x_train,y_train)


SVC()

In [44]:
model.score(x_test,y_test)

0.975925925925926

In [45]:
import pickle
with open('KFold','wb') as f:
    pickle.dump(model,f)