In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline 
from sklearn.datasets import load_wine
wine = load_wine()

In [3]:
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [8]:
df = pd.DataFrame(wine.data,columns = wine.feature_names)
df


alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: fl

In [11]:
df.isnull().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
dtype: int64

In [12]:
df.describe()

alcohol  malic_acid         ash  alcalinity_of_ash   magnesium  \
count  178.000000  178.000000  178.000000         178.000000  178.000000   
mean    13.000618    2.336348    2.366517          19.494944   99.741573   
std      0.811827    1.117146    0.274344           3.339564   14.282484   
min     11.030000    0.740000    1.360000          10.600000   70.000000   
25%     12.362500    1.602500    2.210000          17.200000   88.000000   
50%     13.050000    1.865000    2.360000          19.500000   98.000000   
75%     13.677500    3.082500    2.557500          21.500000  107.000000   
max     14.830000    5.800000    3.230000          30.000000  162.000000   

       total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        2.295112    2.029270              0.361854         1.590899   
std         0.625851    0.998859              0.124453         0.572359   
min         0.980000    0.340000              0.130000         0.410000   
25%         1.742500    1.205000              0.270000         1.250000   
50%         2.355000    2.135000              0.340000         1.555000   
75%         2.800000    2.875000              0.437500         1.950000   
max         3.880000    5.080000              0.660000         3.580000   

       color_intensity         hue  od280/od315_of_diluted_wines      proline  
count       178.000000  178.000000                    178.000000   178.000000  
mean          5.058090    0.957449                      2.611685   746.893258  
std           2.318286    0.228572                      0.709990   314.907474  
min           1.280000    0.480000                      1.270000   278.000000  
25%           3.220000    0.782500                      1.937500   500.500000  
50%           4.690000    0.965000                      2.780000   673.500000  
75%           6.200000    1.120000                      3.170000   985.000000  
max          13.000000    1.710000                      4.000000  1680.000000

In [5]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [13]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [14]:
y = wine.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df,y,test_size =0.1)

In [16]:
x_train

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
146    13.88        5.04  2.23               20.0       80.0           0.98   
154    12.58        1.29  2.10               20.0      103.0           1.48   
72     13.49        1.66  2.24               24.0       87.0           1.88   
32     13.68        1.83  2.36               17.2      104.0           2.42   
34     13.51        1.80  2.65               19.0      110.0           2.35   
..       ...         ...   ...                ...        ...            ...   
48     14.10        2.02  2.40               18.8      103.0           2.75   
115    11.03        1.51  2.20               21.5       85.0           2.46   
129    12.04        4.30  2.38               22.0       80.0           2.10   
21     12.93        3.80  2.65               18.6      102.0           2.41   
9      13.86        1.35  2.27               16.0       98.0           2.98   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
146        0.34                  0.40             0.68             4.90  0.58   
154        0.58                  0.53             1.40             7.60  0.58   
72         1.84                  0.27             1.03             3.74  0.98   
32         2.69                  0.42             1.97             3.84  1.23   
34         2.53                  0.29             1.54             4.20  1.10   
..          ...                   ...              ...              ...   ...   
48         2.92                  0.32             2.38             6.20  1.07   
115        2.17                  0.52             2.01             1.90  1.71   
129        1.75                  0.42             1.35             2.60  0.79   
21         2.41                  0.25             1.98             4.50  1.03   
9          3.15                  0.22             1.85             7.22  1.01   

     od280/od315_of_diluted_wines  proline  
146                          1.33    415.0  
154                          1.55    640.0  
72                           2.78    472.0  
32                           2.87    990.0  
34                           2.87   1095.0  
..                            ...      ...  
48                           2.75   1060.0  
115                          2.87    407.0  
129                          2.57    580.0  
21                           3.52    770.0  
9                            3.55   1045.0  

[160 rows x 13 columns]

In [17]:
len(x_train)

160

In [18]:
len(x_test)

18

In [19]:
from sklearn.naive_bayes import GaussianNB
model1 = GaussianNB()

In [21]:
model1.fit(x_train,y_train)

GaussianNB()

In [22]:
model1.predict(x_test)

array([2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 0, 1, 0, 0, 0, 2, 0, 2])

In [23]:
y_test

array([1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 2, 0, 2])

In [24]:
model1.score(x_test,y_test)

0.8888888888888888

In [25]:
from sklearn.naive_bayes import MultinomialNB
model2 = MultinomialNB()

In [26]:
model2.fit(x_train,y_train)

MultinomialNB()

In [28]:
model2.predict(x_test)

array([1, 2, 2, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 2])

In [29]:
y_test

array([1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 2, 0, 2])

In [30]:
model2.score(x_test,y_test)

0.8333333333333334

In [31]:
from sklearn.model_selection import cross_val_score
model1 = cross_val_score(GaussianNB(),x_train,y_train)
model1

array([1.     , 0.96875, 1.     , 1.     , 1.     ])

In [32]:
model2 = cross_val_score(MultinomialNB(),x_train,y_train)
model2

array([0.8125 , 0.78125, 0.875  , 0.875  , 0.96875])

In [33]:
model1.mean()

0.99375

In [35]:
model2.mean()

0.8625

In [ ]:
import pickle
with open ('Wine_Classfying')